import type { NextPage } from 'next'
import Head from 'next/head'
import Image from 'next/image'
import Link from 'next/link'
import styles from '../styles/Home.module.css'

const Home: NextPage = () => {
  return (
    <>
      <Head>
        <title>Educobot</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <div className={styles.container}>
        <div className={styles.flex_m}>
          <div className={styles.splash}>
            <h1 className={styles.logo}>
              <span className={styles.n1}>e</span>
              <span className={styles.o2}>d</span>
              <span className={styles.n3}>u</span>
              <span className={styles.s4}>c</span>
              <span className={styles.e5}>o</span>
              <span className={styles.n6}>b</span>
              <span className={styles.s7}>o</span>
              <span className={styles.e8}>t</span>
            </h1>
            <span className={styles.shape1}></span>
            <span className={styles.shape2}></span>
            <span className={styles.shape3}></span>
            <span className={styles.shape4}></span>
            <span className={styles.shape5}></span>
            <span className={styles.shape6}></span>
            <span className={styles.shape7}></span>
          </div>
          <div className={`${styles.content} ${styles.padding_top_7rem}`}>
            <h2>
              <span className={styles.block}>A fun game</span>
              <span className={styles.block}>of Educobot.</span>
            </h2>
            <div className={`${styles.content_inner} ${styles.padding_top_2rem} ${styles.padding_bottom_2rem}`}>
              <p>
                Get ready for a fun game of educobot.
              </p>
              <p>
                Use your speech to figure out the jumbled phrase before the timer ends. If you get the answer correctly, you score a point.
              </p>
              <p>
                Try to score as many points as you can.
              </p>
              <div className={styles.padding_top_1rem}>
                <a className={styles.button} target="_blank" href="problems/dog">
                  <span className={styles.sr}>
                    Start Playing Now
                  </span>
                </a>
              </div>
            </div>

          </div>
        </div>
      </div>
    </>
  )
}

export default Home
